// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InterServerProtocol.proto

package Triangle.Protocol;

public final class InterServerProtocol {
  private InterServerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServerUpOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string serverName = 1;
    /**
     * <code>required string serverName = 1;</code>
     */
    boolean hasServerName();
    /**
     * <code>required string serverName = 1;</code>
     */
    java.lang.String getServerName();
    /**
     * <code>required string serverName = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerNameBytes();
  }
  /**
   * Protobuf type {@code Triangle.Protocol.ServerUp}
   */
  public static final class ServerUp extends
      com.google.protobuf.GeneratedMessage
      implements ServerUpOrBuilder {
    // Use ServerUp.newBuilder() to construct.
    private ServerUp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ServerUp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ServerUp defaultInstance;
    public static ServerUp getDefaultInstance() {
      return defaultInstance;
    }

    public ServerUp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ServerUp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serverName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_ServerUp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_ServerUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Triangle.Protocol.InterServerProtocol.ServerUp.class, Triangle.Protocol.InterServerProtocol.ServerUp.Builder.class);
    }

    public static com.google.protobuf.Parser<ServerUp> PARSER =
        new com.google.protobuf.AbstractParser<ServerUp>() {
      public ServerUp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ServerUp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ServerUp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string serverName = 1;
    public static final int SERVERNAME_FIELD_NUMBER = 1;
    private java.lang.Object serverName_;
    /**
     * <code>required string serverName = 1;</code>
     */
    public boolean hasServerName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serverName = 1;</code>
     */
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serverName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServerNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServerNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Triangle.Protocol.InterServerProtocol.ServerUp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Triangle.Protocol.InterServerProtocol.ServerUp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.ServerUp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Triangle.Protocol.InterServerProtocol.ServerUp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.ServerUp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.ServerUp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.ServerUp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.ServerUp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.ServerUp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.ServerUp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Triangle.Protocol.InterServerProtocol.ServerUp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Triangle.Protocol.ServerUp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Triangle.Protocol.InterServerProtocol.ServerUpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_ServerUp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_ServerUp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Triangle.Protocol.InterServerProtocol.ServerUp.class, Triangle.Protocol.InterServerProtocol.ServerUp.Builder.class);
      }

      // Construct using Triangle.Protocol.InterServerProtocol.ServerUp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_ServerUp_descriptor;
      }

      public Triangle.Protocol.InterServerProtocol.ServerUp getDefaultInstanceForType() {
        return Triangle.Protocol.InterServerProtocol.ServerUp.getDefaultInstance();
      }

      public Triangle.Protocol.InterServerProtocol.ServerUp build() {
        Triangle.Protocol.InterServerProtocol.ServerUp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Triangle.Protocol.InterServerProtocol.ServerUp buildPartial() {
        Triangle.Protocol.InterServerProtocol.ServerUp result = new Triangle.Protocol.InterServerProtocol.ServerUp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverName_ = serverName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Triangle.Protocol.InterServerProtocol.ServerUp) {
          return mergeFrom((Triangle.Protocol.InterServerProtocol.ServerUp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Triangle.Protocol.InterServerProtocol.ServerUp other) {
        if (other == Triangle.Protocol.InterServerProtocol.ServerUp.getDefaultInstance()) return this;
        if (other.hasServerName()) {
          bitField0_ |= 0x00000001;
          serverName_ = other.serverName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Triangle.Protocol.InterServerProtocol.ServerUp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Triangle.Protocol.InterServerProtocol.ServerUp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string serverName = 1;
      private java.lang.Object serverName_ = "";
      /**
       * <code>required string serverName = 1;</code>
       */
      public boolean hasServerName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public java.lang.String getServerName() {
        java.lang.Object ref = serverName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        java.lang.Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public Builder setServerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public Builder clearServerName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverName_ = getDefaultInstance().getServerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Triangle.Protocol.ServerUp)
    }

    static {
      defaultInstance = new ServerUp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Triangle.Protocol.ServerUp)
  }

  public interface HeartBeatOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string serverName = 1;
    /**
     * <code>required string serverName = 1;</code>
     */
    boolean hasServerName();
    /**
     * <code>required string serverName = 1;</code>
     */
    java.lang.String getServerName();
    /**
     * <code>required string serverName = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerNameBytes();
  }
  /**
   * Protobuf type {@code Triangle.Protocol.HeartBeat}
   */
  public static final class HeartBeat extends
      com.google.protobuf.GeneratedMessage
      implements HeartBeatOrBuilder {
    // Use HeartBeat.newBuilder() to construct.
    private HeartBeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeat defaultInstance;
    public static HeartBeat getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serverName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_HeartBeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_HeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Triangle.Protocol.InterServerProtocol.HeartBeat.class, Triangle.Protocol.InterServerProtocol.HeartBeat.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeat> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeat>() {
      public HeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string serverName = 1;
    public static final int SERVERNAME_FIELD_NUMBER = 1;
    private java.lang.Object serverName_;
    /**
     * <code>required string serverName = 1;</code>
     */
    public boolean hasServerName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serverName = 1;</code>
     */
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      serverName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasServerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServerNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServerNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Triangle.Protocol.InterServerProtocol.HeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Triangle.Protocol.InterServerProtocol.HeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.HeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Triangle.Protocol.InterServerProtocol.HeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.HeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.HeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.HeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.HeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Triangle.Protocol.InterServerProtocol.HeartBeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Triangle.Protocol.HeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Triangle.Protocol.InterServerProtocol.HeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_HeartBeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_HeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Triangle.Protocol.InterServerProtocol.HeartBeat.class, Triangle.Protocol.InterServerProtocol.HeartBeat.Builder.class);
      }

      // Construct using Triangle.Protocol.InterServerProtocol.HeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_HeartBeat_descriptor;
      }

      public Triangle.Protocol.InterServerProtocol.HeartBeat getDefaultInstanceForType() {
        return Triangle.Protocol.InterServerProtocol.HeartBeat.getDefaultInstance();
      }

      public Triangle.Protocol.InterServerProtocol.HeartBeat build() {
        Triangle.Protocol.InterServerProtocol.HeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Triangle.Protocol.InterServerProtocol.HeartBeat buildPartial() {
        Triangle.Protocol.InterServerProtocol.HeartBeat result = new Triangle.Protocol.InterServerProtocol.HeartBeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverName_ = serverName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Triangle.Protocol.InterServerProtocol.HeartBeat) {
          return mergeFrom((Triangle.Protocol.InterServerProtocol.HeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Triangle.Protocol.InterServerProtocol.HeartBeat other) {
        if (other == Triangle.Protocol.InterServerProtocol.HeartBeat.getDefaultInstance()) return this;
        if (other.hasServerName()) {
          bitField0_ |= 0x00000001;
          serverName_ = other.serverName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Triangle.Protocol.InterServerProtocol.HeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Triangle.Protocol.InterServerProtocol.HeartBeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string serverName = 1;
      private java.lang.Object serverName_ = "";
      /**
       * <code>required string serverName = 1;</code>
       */
      public boolean hasServerName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public java.lang.String getServerName() {
        java.lang.Object ref = serverName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serverName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        java.lang.Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public Builder setServerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public Builder clearServerName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverName_ = getDefaultInstance().getServerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Triangle.Protocol.HeartBeat)
    }

    static {
      defaultInstance = new HeartBeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Triangle.Protocol.HeartBeat)
  }

  public interface JoinLeaveOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 accountNumber = 1;
    /**
     * <code>required int32 accountNumber = 1;</code>
     */
    boolean hasAccountNumber();
    /**
     * <code>required int32 accountNumber = 1;</code>
     */
    int getAccountNumber();
  }
  /**
   * Protobuf type {@code Triangle.Protocol.JoinLeave}
   */
  public static final class JoinLeave extends
      com.google.protobuf.GeneratedMessage
      implements JoinLeaveOrBuilder {
    // Use JoinLeave.newBuilder() to construct.
    private JoinLeave(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JoinLeave(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JoinLeave defaultInstance;
    public static JoinLeave getDefaultInstance() {
      return defaultInstance;
    }

    public JoinLeave getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JoinLeave(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accountNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_JoinLeave_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_JoinLeave_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Triangle.Protocol.InterServerProtocol.JoinLeave.class, Triangle.Protocol.InterServerProtocol.JoinLeave.Builder.class);
    }

    public static com.google.protobuf.Parser<JoinLeave> PARSER =
        new com.google.protobuf.AbstractParser<JoinLeave>() {
      public JoinLeave parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinLeave(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JoinLeave> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 accountNumber = 1;
    public static final int ACCOUNTNUMBER_FIELD_NUMBER = 1;
    private int accountNumber_;
    /**
     * <code>required int32 accountNumber = 1;</code>
     */
    public boolean hasAccountNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 accountNumber = 1;</code>
     */
    public int getAccountNumber() {
      return accountNumber_;
    }

    private void initFields() {
      accountNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAccountNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, accountNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, accountNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Triangle.Protocol.InterServerProtocol.JoinLeave parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Triangle.Protocol.InterServerProtocol.JoinLeave parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.JoinLeave parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Triangle.Protocol.InterServerProtocol.JoinLeave parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.JoinLeave parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.JoinLeave parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.JoinLeave parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.JoinLeave parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.JoinLeave parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.JoinLeave parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Triangle.Protocol.InterServerProtocol.JoinLeave prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Triangle.Protocol.JoinLeave}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Triangle.Protocol.InterServerProtocol.JoinLeaveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_JoinLeave_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_JoinLeave_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Triangle.Protocol.InterServerProtocol.JoinLeave.class, Triangle.Protocol.InterServerProtocol.JoinLeave.Builder.class);
      }

      // Construct using Triangle.Protocol.InterServerProtocol.JoinLeave.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_JoinLeave_descriptor;
      }

      public Triangle.Protocol.InterServerProtocol.JoinLeave getDefaultInstanceForType() {
        return Triangle.Protocol.InterServerProtocol.JoinLeave.getDefaultInstance();
      }

      public Triangle.Protocol.InterServerProtocol.JoinLeave build() {
        Triangle.Protocol.InterServerProtocol.JoinLeave result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Triangle.Protocol.InterServerProtocol.JoinLeave buildPartial() {
        Triangle.Protocol.InterServerProtocol.JoinLeave result = new Triangle.Protocol.InterServerProtocol.JoinLeave(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountNumber_ = accountNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Triangle.Protocol.InterServerProtocol.JoinLeave) {
          return mergeFrom((Triangle.Protocol.InterServerProtocol.JoinLeave)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Triangle.Protocol.InterServerProtocol.JoinLeave other) {
        if (other == Triangle.Protocol.InterServerProtocol.JoinLeave.getDefaultInstance()) return this;
        if (other.hasAccountNumber()) {
          setAccountNumber(other.getAccountNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountNumber()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Triangle.Protocol.InterServerProtocol.JoinLeave parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Triangle.Protocol.InterServerProtocol.JoinLeave) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 accountNumber = 1;
      private int accountNumber_ ;
      /**
       * <code>required int32 accountNumber = 1;</code>
       */
      public boolean hasAccountNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 accountNumber = 1;</code>
       */
      public int getAccountNumber() {
        return accountNumber_;
      }
      /**
       * <code>required int32 accountNumber = 1;</code>
       */
      public Builder setAccountNumber(int value) {
        bitField0_ |= 0x00000001;
        accountNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 accountNumber = 1;</code>
       */
      public Builder clearAccountNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Triangle.Protocol.JoinLeave)
    }

    static {
      defaultInstance = new JoinLeave(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Triangle.Protocol.JoinLeave)
  }

  public interface InterServerMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;
    /**
     * <code>required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;</code>
     */
    boolean hasInterServerMessageType();
    /**
     * <code>required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;</code>
     */
    Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType getInterServerMessageType();

    // optional .Triangle.Protocol.JoinLeave joinleave = 2;
    /**
     * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
     */
    boolean hasJoinleave();
    /**
     * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
     */
    Triangle.Protocol.InterServerProtocol.JoinLeave getJoinleave();
    /**
     * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
     */
    Triangle.Protocol.InterServerProtocol.JoinLeaveOrBuilder getJoinleaveOrBuilder();

    // optional .Triangle.Protocol.ServerUp serverUp = 1;
    /**
     * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
     */
    boolean hasServerUp();
    /**
     * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
     */
    Triangle.Protocol.InterServerProtocol.ServerUp getServerUp();
    /**
     * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
     */
    Triangle.Protocol.InterServerProtocol.ServerUpOrBuilder getServerUpOrBuilder();

    // optional .Triangle.Protocol.HeartBeat heartBeat = 7;
    /**
     * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
     */
    boolean hasHeartBeat();
    /**
     * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
     */
    Triangle.Protocol.InterServerProtocol.HeartBeat getHeartBeat();
    /**
     * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
     */
    Triangle.Protocol.InterServerProtocol.HeartBeatOrBuilder getHeartBeatOrBuilder();
  }
  /**
   * Protobuf type {@code Triangle.Protocol.InterServerMessage}
   */
  public static final class InterServerMessage extends
      com.google.protobuf.GeneratedMessage
      implements InterServerMessageOrBuilder {
    // Use InterServerMessage.newBuilder() to construct.
    private InterServerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private InterServerMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final InterServerMessage defaultInstance;
    public static InterServerMessage getDefaultInstance() {
      return defaultInstance;
    }

    public InterServerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private InterServerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Triangle.Protocol.InterServerProtocol.ServerUp.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = serverUp_.toBuilder();
              }
              serverUp_ = input.readMessage(Triangle.Protocol.InterServerProtocol.ServerUp.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(serverUp_);
                serverUp_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 18: {
              Triangle.Protocol.InterServerProtocol.JoinLeave.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = joinleave_.toBuilder();
              }
              joinleave_ = input.readMessage(Triangle.Protocol.InterServerProtocol.JoinLeave.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(joinleave_);
                joinleave_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 58: {
              Triangle.Protocol.InterServerProtocol.HeartBeat.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = heartBeat_.toBuilder();
              }
              heartBeat_ = input.readMessage(Triangle.Protocol.InterServerProtocol.HeartBeat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartBeat_);
                heartBeat_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 800: {
              int rawValue = input.readEnum();
              Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType value = Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(100, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                interServerMessageType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_InterServerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_InterServerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Triangle.Protocol.InterServerProtocol.InterServerMessage.class, Triangle.Protocol.InterServerProtocol.InterServerMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<InterServerMessage> PARSER =
        new com.google.protobuf.AbstractParser<InterServerMessage>() {
      public InterServerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InterServerMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InterServerMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Triangle.Protocol.InterServerMessage.InterServerMessageType}
     */
    public enum InterServerMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Join = 2;</code>
       */
      Join(0, 2),
      /**
       * <code>Leave = 3;</code>
       */
      Leave(1, 3),
      /**
       * <code>ServerUp = 1;</code>
       */
      ServerUp(2, 1),
      /**
       * <code>HeartBeat = 7;</code>
       */
      HeartBeat(3, 7),
      ;

      /**
       * <code>Join = 2;</code>
       */
      public static final int Join_VALUE = 2;
      /**
       * <code>Leave = 3;</code>
       */
      public static final int Leave_VALUE = 3;
      /**
       * <code>ServerUp = 1;</code>
       */
      public static final int ServerUp_VALUE = 1;
      /**
       * <code>HeartBeat = 7;</code>
       */
      public static final int HeartBeat_VALUE = 7;


      public final int getNumber() { return value; }

      public static InterServerMessageType valueOf(int value) {
        switch (value) {
          case 2: return Join;
          case 3: return Leave;
          case 1: return ServerUp;
          case 7: return HeartBeat;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<InterServerMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<InterServerMessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<InterServerMessageType>() {
              public InterServerMessageType findValueByNumber(int number) {
                return InterServerMessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Triangle.Protocol.InterServerProtocol.InterServerMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final InterServerMessageType[] VALUES = values();

      public static InterServerMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private InterServerMessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Triangle.Protocol.InterServerMessage.InterServerMessageType)
    }

    private int bitField0_;
    // required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;
    public static final int INTERSERVERMESSAGETYPE_FIELD_NUMBER = 100;
    private Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType interServerMessageType_;
    /**
     * <code>required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;</code>
     */
    public boolean hasInterServerMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;</code>
     */
    public Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType getInterServerMessageType() {
      return interServerMessageType_;
    }

    // optional .Triangle.Protocol.JoinLeave joinleave = 2;
    public static final int JOINLEAVE_FIELD_NUMBER = 2;
    private Triangle.Protocol.InterServerProtocol.JoinLeave joinleave_;
    /**
     * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
     */
    public boolean hasJoinleave() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
     */
    public Triangle.Protocol.InterServerProtocol.JoinLeave getJoinleave() {
      return joinleave_;
    }
    /**
     * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
     */
    public Triangle.Protocol.InterServerProtocol.JoinLeaveOrBuilder getJoinleaveOrBuilder() {
      return joinleave_;
    }

    // optional .Triangle.Protocol.ServerUp serverUp = 1;
    public static final int SERVERUP_FIELD_NUMBER = 1;
    private Triangle.Protocol.InterServerProtocol.ServerUp serverUp_;
    /**
     * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
     */
    public boolean hasServerUp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
     */
    public Triangle.Protocol.InterServerProtocol.ServerUp getServerUp() {
      return serverUp_;
    }
    /**
     * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
     */
    public Triangle.Protocol.InterServerProtocol.ServerUpOrBuilder getServerUpOrBuilder() {
      return serverUp_;
    }

    // optional .Triangle.Protocol.HeartBeat heartBeat = 7;
    public static final int HEARTBEAT_FIELD_NUMBER = 7;
    private Triangle.Protocol.InterServerProtocol.HeartBeat heartBeat_;
    /**
     * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
     */
    public boolean hasHeartBeat() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
     */
    public Triangle.Protocol.InterServerProtocol.HeartBeat getHeartBeat() {
      return heartBeat_;
    }
    /**
     * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
     */
    public Triangle.Protocol.InterServerProtocol.HeartBeatOrBuilder getHeartBeatOrBuilder() {
      return heartBeat_;
    }

    private void initFields() {
      interServerMessageType_ = Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType.Join;
      joinleave_ = Triangle.Protocol.InterServerProtocol.JoinLeave.getDefaultInstance();
      serverUp_ = Triangle.Protocol.InterServerProtocol.ServerUp.getDefaultInstance();
      heartBeat_ = Triangle.Protocol.InterServerProtocol.HeartBeat.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasInterServerMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasJoinleave()) {
        if (!getJoinleave().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasServerUp()) {
        if (!getServerUp().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeartBeat()) {
        if (!getHeartBeat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(1, serverUp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, joinleave_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(7, heartBeat_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(100, interServerMessageType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, serverUp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, joinleave_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, heartBeat_);
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(100, interServerMessageType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Triangle.Protocol.InterServerProtocol.InterServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Triangle.Protocol.InterServerProtocol.InterServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.InterServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Triangle.Protocol.InterServerProtocol.InterServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.InterServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.InterServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.InterServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.InterServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Triangle.Protocol.InterServerProtocol.InterServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Triangle.Protocol.InterServerProtocol.InterServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Triangle.Protocol.InterServerProtocol.InterServerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Triangle.Protocol.InterServerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Triangle.Protocol.InterServerProtocol.InterServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_InterServerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_InterServerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Triangle.Protocol.InterServerProtocol.InterServerMessage.class, Triangle.Protocol.InterServerProtocol.InterServerMessage.Builder.class);
      }

      // Construct using Triangle.Protocol.InterServerProtocol.InterServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getJoinleaveFieldBuilder();
          getServerUpFieldBuilder();
          getHeartBeatFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        interServerMessageType_ = Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType.Join;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (joinleaveBuilder_ == null) {
          joinleave_ = Triangle.Protocol.InterServerProtocol.JoinLeave.getDefaultInstance();
        } else {
          joinleaveBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (serverUpBuilder_ == null) {
          serverUp_ = Triangle.Protocol.InterServerProtocol.ServerUp.getDefaultInstance();
        } else {
          serverUpBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (heartBeatBuilder_ == null) {
          heartBeat_ = Triangle.Protocol.InterServerProtocol.HeartBeat.getDefaultInstance();
        } else {
          heartBeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Triangle.Protocol.InterServerProtocol.internal_static_Triangle_Protocol_InterServerMessage_descriptor;
      }

      public Triangle.Protocol.InterServerProtocol.InterServerMessage getDefaultInstanceForType() {
        return Triangle.Protocol.InterServerProtocol.InterServerMessage.getDefaultInstance();
      }

      public Triangle.Protocol.InterServerProtocol.InterServerMessage build() {
        Triangle.Protocol.InterServerProtocol.InterServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Triangle.Protocol.InterServerProtocol.InterServerMessage buildPartial() {
        Triangle.Protocol.InterServerProtocol.InterServerMessage result = new Triangle.Protocol.InterServerProtocol.InterServerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.interServerMessageType_ = interServerMessageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (joinleaveBuilder_ == null) {
          result.joinleave_ = joinleave_;
        } else {
          result.joinleave_ = joinleaveBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (serverUpBuilder_ == null) {
          result.serverUp_ = serverUp_;
        } else {
          result.serverUp_ = serverUpBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (heartBeatBuilder_ == null) {
          result.heartBeat_ = heartBeat_;
        } else {
          result.heartBeat_ = heartBeatBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Triangle.Protocol.InterServerProtocol.InterServerMessage) {
          return mergeFrom((Triangle.Protocol.InterServerProtocol.InterServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Triangle.Protocol.InterServerProtocol.InterServerMessage other) {
        if (other == Triangle.Protocol.InterServerProtocol.InterServerMessage.getDefaultInstance()) return this;
        if (other.hasInterServerMessageType()) {
          setInterServerMessageType(other.getInterServerMessageType());
        }
        if (other.hasJoinleave()) {
          mergeJoinleave(other.getJoinleave());
        }
        if (other.hasServerUp()) {
          mergeServerUp(other.getServerUp());
        }
        if (other.hasHeartBeat()) {
          mergeHeartBeat(other.getHeartBeat());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasInterServerMessageType()) {
          
          return false;
        }
        if (hasJoinleave()) {
          if (!getJoinleave().isInitialized()) {
            
            return false;
          }
        }
        if (hasServerUp()) {
          if (!getServerUp().isInitialized()) {
            
            return false;
          }
        }
        if (hasHeartBeat()) {
          if (!getHeartBeat().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Triangle.Protocol.InterServerProtocol.InterServerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Triangle.Protocol.InterServerProtocol.InterServerMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;
      private Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType interServerMessageType_ = Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType.Join;
      /**
       * <code>required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;</code>
       */
      public boolean hasInterServerMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;</code>
       */
      public Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType getInterServerMessageType() {
        return interServerMessageType_;
      }
      /**
       * <code>required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;</code>
       */
      public Builder setInterServerMessageType(Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        interServerMessageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .Triangle.Protocol.InterServerMessage.InterServerMessageType interServerMessageType = 100;</code>
       */
      public Builder clearInterServerMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        interServerMessageType_ = Triangle.Protocol.InterServerProtocol.InterServerMessage.InterServerMessageType.Join;
        onChanged();
        return this;
      }

      // optional .Triangle.Protocol.JoinLeave joinleave = 2;
      private Triangle.Protocol.InterServerProtocol.JoinLeave joinleave_ = Triangle.Protocol.InterServerProtocol.JoinLeave.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Triangle.Protocol.InterServerProtocol.JoinLeave, Triangle.Protocol.InterServerProtocol.JoinLeave.Builder, Triangle.Protocol.InterServerProtocol.JoinLeaveOrBuilder> joinleaveBuilder_;
      /**
       * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
       */
      public boolean hasJoinleave() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
       */
      public Triangle.Protocol.InterServerProtocol.JoinLeave getJoinleave() {
        if (joinleaveBuilder_ == null) {
          return joinleave_;
        } else {
          return joinleaveBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
       */
      public Builder setJoinleave(Triangle.Protocol.InterServerProtocol.JoinLeave value) {
        if (joinleaveBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          joinleave_ = value;
          onChanged();
        } else {
          joinleaveBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
       */
      public Builder setJoinleave(
          Triangle.Protocol.InterServerProtocol.JoinLeave.Builder builderForValue) {
        if (joinleaveBuilder_ == null) {
          joinleave_ = builderForValue.build();
          onChanged();
        } else {
          joinleaveBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
       */
      public Builder mergeJoinleave(Triangle.Protocol.InterServerProtocol.JoinLeave value) {
        if (joinleaveBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              joinleave_ != Triangle.Protocol.InterServerProtocol.JoinLeave.getDefaultInstance()) {
            joinleave_ =
              Triangle.Protocol.InterServerProtocol.JoinLeave.newBuilder(joinleave_).mergeFrom(value).buildPartial();
          } else {
            joinleave_ = value;
          }
          onChanged();
        } else {
          joinleaveBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
       */
      public Builder clearJoinleave() {
        if (joinleaveBuilder_ == null) {
          joinleave_ = Triangle.Protocol.InterServerProtocol.JoinLeave.getDefaultInstance();
          onChanged();
        } else {
          joinleaveBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
       */
      public Triangle.Protocol.InterServerProtocol.JoinLeave.Builder getJoinleaveBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getJoinleaveFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
       */
      public Triangle.Protocol.InterServerProtocol.JoinLeaveOrBuilder getJoinleaveOrBuilder() {
        if (joinleaveBuilder_ != null) {
          return joinleaveBuilder_.getMessageOrBuilder();
        } else {
          return joinleave_;
        }
      }
      /**
       * <code>optional .Triangle.Protocol.JoinLeave joinleave = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Triangle.Protocol.InterServerProtocol.JoinLeave, Triangle.Protocol.InterServerProtocol.JoinLeave.Builder, Triangle.Protocol.InterServerProtocol.JoinLeaveOrBuilder> 
          getJoinleaveFieldBuilder() {
        if (joinleaveBuilder_ == null) {
          joinleaveBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Triangle.Protocol.InterServerProtocol.JoinLeave, Triangle.Protocol.InterServerProtocol.JoinLeave.Builder, Triangle.Protocol.InterServerProtocol.JoinLeaveOrBuilder>(
                  joinleave_,
                  getParentForChildren(),
                  isClean());
          joinleave_ = null;
        }
        return joinleaveBuilder_;
      }

      // optional .Triangle.Protocol.ServerUp serverUp = 1;
      private Triangle.Protocol.InterServerProtocol.ServerUp serverUp_ = Triangle.Protocol.InterServerProtocol.ServerUp.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Triangle.Protocol.InterServerProtocol.ServerUp, Triangle.Protocol.InterServerProtocol.ServerUp.Builder, Triangle.Protocol.InterServerProtocol.ServerUpOrBuilder> serverUpBuilder_;
      /**
       * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
       */
      public boolean hasServerUp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
       */
      public Triangle.Protocol.InterServerProtocol.ServerUp getServerUp() {
        if (serverUpBuilder_ == null) {
          return serverUp_;
        } else {
          return serverUpBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
       */
      public Builder setServerUp(Triangle.Protocol.InterServerProtocol.ServerUp value) {
        if (serverUpBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          serverUp_ = value;
          onChanged();
        } else {
          serverUpBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
       */
      public Builder setServerUp(
          Triangle.Protocol.InterServerProtocol.ServerUp.Builder builderForValue) {
        if (serverUpBuilder_ == null) {
          serverUp_ = builderForValue.build();
          onChanged();
        } else {
          serverUpBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
       */
      public Builder mergeServerUp(Triangle.Protocol.InterServerProtocol.ServerUp value) {
        if (serverUpBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              serverUp_ != Triangle.Protocol.InterServerProtocol.ServerUp.getDefaultInstance()) {
            serverUp_ =
              Triangle.Protocol.InterServerProtocol.ServerUp.newBuilder(serverUp_).mergeFrom(value).buildPartial();
          } else {
            serverUp_ = value;
          }
          onChanged();
        } else {
          serverUpBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
       */
      public Builder clearServerUp() {
        if (serverUpBuilder_ == null) {
          serverUp_ = Triangle.Protocol.InterServerProtocol.ServerUp.getDefaultInstance();
          onChanged();
        } else {
          serverUpBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
       */
      public Triangle.Protocol.InterServerProtocol.ServerUp.Builder getServerUpBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getServerUpFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
       */
      public Triangle.Protocol.InterServerProtocol.ServerUpOrBuilder getServerUpOrBuilder() {
        if (serverUpBuilder_ != null) {
          return serverUpBuilder_.getMessageOrBuilder();
        } else {
          return serverUp_;
        }
      }
      /**
       * <code>optional .Triangle.Protocol.ServerUp serverUp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Triangle.Protocol.InterServerProtocol.ServerUp, Triangle.Protocol.InterServerProtocol.ServerUp.Builder, Triangle.Protocol.InterServerProtocol.ServerUpOrBuilder> 
          getServerUpFieldBuilder() {
        if (serverUpBuilder_ == null) {
          serverUpBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Triangle.Protocol.InterServerProtocol.ServerUp, Triangle.Protocol.InterServerProtocol.ServerUp.Builder, Triangle.Protocol.InterServerProtocol.ServerUpOrBuilder>(
                  serverUp_,
                  getParentForChildren(),
                  isClean());
          serverUp_ = null;
        }
        return serverUpBuilder_;
      }

      // optional .Triangle.Protocol.HeartBeat heartBeat = 7;
      private Triangle.Protocol.InterServerProtocol.HeartBeat heartBeat_ = Triangle.Protocol.InterServerProtocol.HeartBeat.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Triangle.Protocol.InterServerProtocol.HeartBeat, Triangle.Protocol.InterServerProtocol.HeartBeat.Builder, Triangle.Protocol.InterServerProtocol.HeartBeatOrBuilder> heartBeatBuilder_;
      /**
       * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
       */
      public boolean hasHeartBeat() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
       */
      public Triangle.Protocol.InterServerProtocol.HeartBeat getHeartBeat() {
        if (heartBeatBuilder_ == null) {
          return heartBeat_;
        } else {
          return heartBeatBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
       */
      public Builder setHeartBeat(Triangle.Protocol.InterServerProtocol.HeartBeat value) {
        if (heartBeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartBeat_ = value;
          onChanged();
        } else {
          heartBeatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
       */
      public Builder setHeartBeat(
          Triangle.Protocol.InterServerProtocol.HeartBeat.Builder builderForValue) {
        if (heartBeatBuilder_ == null) {
          heartBeat_ = builderForValue.build();
          onChanged();
        } else {
          heartBeatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
       */
      public Builder mergeHeartBeat(Triangle.Protocol.InterServerProtocol.HeartBeat value) {
        if (heartBeatBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              heartBeat_ != Triangle.Protocol.InterServerProtocol.HeartBeat.getDefaultInstance()) {
            heartBeat_ =
              Triangle.Protocol.InterServerProtocol.HeartBeat.newBuilder(heartBeat_).mergeFrom(value).buildPartial();
          } else {
            heartBeat_ = value;
          }
          onChanged();
        } else {
          heartBeatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
       */
      public Builder clearHeartBeat() {
        if (heartBeatBuilder_ == null) {
          heartBeat_ = Triangle.Protocol.InterServerProtocol.HeartBeat.getDefaultInstance();
          onChanged();
        } else {
          heartBeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
       */
      public Triangle.Protocol.InterServerProtocol.HeartBeat.Builder getHeartBeatBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getHeartBeatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
       */
      public Triangle.Protocol.InterServerProtocol.HeartBeatOrBuilder getHeartBeatOrBuilder() {
        if (heartBeatBuilder_ != null) {
          return heartBeatBuilder_.getMessageOrBuilder();
        } else {
          return heartBeat_;
        }
      }
      /**
       * <code>optional .Triangle.Protocol.HeartBeat heartBeat = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Triangle.Protocol.InterServerProtocol.HeartBeat, Triangle.Protocol.InterServerProtocol.HeartBeat.Builder, Triangle.Protocol.InterServerProtocol.HeartBeatOrBuilder> 
          getHeartBeatFieldBuilder() {
        if (heartBeatBuilder_ == null) {
          heartBeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Triangle.Protocol.InterServerProtocol.HeartBeat, Triangle.Protocol.InterServerProtocol.HeartBeat.Builder, Triangle.Protocol.InterServerProtocol.HeartBeatOrBuilder>(
                  heartBeat_,
                  getParentForChildren(),
                  isClean());
          heartBeat_ = null;
        }
        return heartBeatBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Triangle.Protocol.InterServerMessage)
    }

    static {
      defaultInstance = new InterServerMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Triangle.Protocol.InterServerMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Triangle_Protocol_ServerUp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Triangle_Protocol_ServerUp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Triangle_Protocol_HeartBeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Triangle_Protocol_HeartBeat_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Triangle_Protocol_JoinLeave_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Triangle_Protocol_JoinLeave_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Triangle_Protocol_InterServerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Triangle_Protocol_InterServerMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031InterServerProtocol.proto\022\021Triangle.Pr" +
      "otocol\"\036\n\010ServerUp\022\022\n\nserverName\030\001 \002(\t\"\037" +
      "\n\tHeartBeat\022\022\n\nserverName\030\001 \002(\t\"\"\n\tJoinL" +
      "eave\022\025\n\raccountNumber\030\001 \002(\005\"\317\002\n\022InterSer" +
      "verMessage\022\\\n\026interServerMessageType\030d \002" +
      "(\0162<.Triangle.Protocol.InterServerMessag" +
      "e.InterServerMessageType\022/\n\tjoinleave\030\002 " +
      "\001(\0132\034.Triangle.Protocol.JoinLeave\022-\n\010ser" +
      "verUp\030\001 \001(\0132\033.Triangle.Protocol.ServerUp" +
      "\022/\n\theartBeat\030\007 \001(\0132\034.Triangle.Protocol.",
      "HeartBeat\"J\n\026InterServerMessageType\022\010\n\004J" +
      "oin\020\002\022\t\n\005Leave\020\003\022\014\n\010ServerUp\020\001\022\r\n\tHeartB" +
      "eat\020\007B(\n\021Triangle.ProtocolB\023InterServerP" +
      "rotocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Triangle_Protocol_ServerUp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Triangle_Protocol_ServerUp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Triangle_Protocol_ServerUp_descriptor,
              new java.lang.String[] { "ServerName", });
          internal_static_Triangle_Protocol_HeartBeat_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Triangle_Protocol_HeartBeat_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Triangle_Protocol_HeartBeat_descriptor,
              new java.lang.String[] { "ServerName", });
          internal_static_Triangle_Protocol_JoinLeave_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Triangle_Protocol_JoinLeave_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Triangle_Protocol_JoinLeave_descriptor,
              new java.lang.String[] { "AccountNumber", });
          internal_static_Triangle_Protocol_InterServerMessage_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Triangle_Protocol_InterServerMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Triangle_Protocol_InterServerMessage_descriptor,
              new java.lang.String[] { "InterServerMessageType", "Joinleave", "ServerUp", "HeartBeat", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
